### ISSUE TITLE
JDKs with a space in the path do not work.

### ISSUE THREAD

**Issue by jamesamurr-bind** [FelixSelter/JEnv-for-Windows#1]
Tried to add jdk path that has a space in it. The list operation doesn't show the full path.
Example: 
Run this:
jenv.bat add jdk8 "C:\Program Files\AdoptOpenJDK\jdk-8.0.292.10-hotspot"
Then this:
jenv.bat list
Output is this:
jdk8|"C:\Program

output should be:
jdk8|"C:\Program Files\AdoptOpenJDK\jdk-8.0.292.10-hotspot"

**Comment by FelixSelter** [comment]
I cannot confirm. I downloaded the latest bat file and run your command and was able to get the desired results. However, if you forgot the quotation marks your output is produced. To avoid further mistakes I fixed a spelling mistake and modified the script so it exits after a Syntax error.

If your problem persists after downloading the latest variant please add a Video showing every action in detail.

Thanks for your contribution
Felix Selter

**Comment by FelixSelter** [comment]
You may confirm if this can be closed?

**Comment by jamesamurr-bind** [comment]
Apologies for the late reply. The list command behaves correctly now. Thanks for making this!
