### ISSUE TITLE
The file jenv.ps1 is not digitally signed

### ISSUE THREAD

**Issue by cdecinkoKnight** [FelixSelter/JEnv-for-Windows#13]
File C:\Programs\JEnv-for-Windows\jenv.ps1 cannot be loaded. The file C:\Programs\JEnv-for-Windows\jenv.ps1 is not
digitally signed. You cannot run this script on the current system. For more information about running scripts and
setting execution policy, see about_Execution_Policies at https:/go.microsoft.com/fwlink/?LinkID=135170.
    + CategoryInfo          : SecurityError: (:) [], ParentContainsErrorRecordException
    + FullyQualifiedErrorId : UnauthorizedAccess

**Comment by FelixSelter** [comment]
Please refer to https://stackoverflow.com/questions/9742775/why-is-my-locally-created-script-not-allowed-to-run-under-the-remotesigned-execu and the microsoft link from the error message.

You will have to permit the script. I suggest you use the .bat file as this should remotesign the ps script

**Comment by FelixSelter** [comment]
Can I close this now?

**Comment by Marcuse7** [comment]
I know this issue is closed but what helped me was removing the "_this file came from another computer_" flag from all blocked files. This can be done manually in File Explorer or by executing a PowerShell command in the folder where JEnv is installed: 

``` powershell
Get-ChildItem -File -Include "*.exe","*.bat","*.ps1","*.psm1" -Recurse | ForEach { Unblock-File -LiteralPath $_.FullName }
```
