### ISSUE TITLE
Cannot add Java in folder with space

### ISSUE THREAD

**Issue by cdecinkoKnight** [FelixSelter/JEnv-for-Windows#14]
My folder has a space in the name. Jenv is not finding the java file.

jenv add C:\Program Files\Java\jre1.8.0_311
The specified path is not a valid JAVA_HOME. File not found:
Files\Java\jre1.8.0_311\bin\java.exe

I also tried the short name and that also fails.

**Comment by FelixSelter** [comment]
you have to wrap the path into parentheses. jenv add „C:\Program Files\Java\jre1.8.0_311“

**Comment by FelixSelter** [comment]
Can I close this now?
