### ISSUE TITLE
jenv use copies the entire system PATH variable to user PATH

### ISSUE THREAD

**Issue by huangxg** [FelixSelter/JEnv-for-Windows#15]
After I ran `jenv use`, the entire system PATH variable was copied to user PATH.

Expected behavior: the command does not copy any value from system PATH to user PATH; just adjusts JAVA related value on user PATH.

**Comment by FelixSelter** [comment]
Sorry for letting you wait for so long.
However, I can not confirm your issue.
I know there was such a problem with an older version of jenv.
Are you using the latest version

**Comment by FelixSelter** [comment]
I checked again. Your right.

**Comment by FelixSelter** [comment]
Thank you for your contribution. And again sorry for my late reply
