### ISSUE TITLE
Please, make releases

### ISSUE THREAD

**Issue by bkmeneguello** [FelixSelter/JEnv-for-Windows#16]
I'm creating a `scoop` manifest but it's better when there are releases to download the artifacts.

**Comment by FelixSelter** [comment]
Is it fine like this? https://github.com/FelixSelter/JEnv-for-Windows/releases/tag/V1.0.0

**Comment by bkmeneguello** [comment]
It works, but if you want to be more kind, it would be better to push a zip to the release containing only the files in the release (and maybe any required metadata like LICENCE, but removing any `.gitignore` and maybe the README.md). This way it can be unzipped to the installation dir and just added to the PATH.

**Comment by FelixSelter** [comment]
is it fine now?

**Comment by FelixSelter** [comment]
I am closing this now as a new release is automatically created when someone pushes with a version tag. That release contains a zip file named "JEnv.zip" which contains the code required to run the application. See here for an example: https://github.com/FelixSelter/JEnv-for-Windows/releases/tag/v2.0.206
