### ISSUE TITLE
jenv.config should be created in $Env:APPDATA\JEnv\jenv.config

### ISSUE THREAD

**Issue by bkmeneguello** [FelixSelter/JEnv-for-Windows#17]
https://github.com/FelixSelter/JEnv-for-Windows/blob/1697ae4346dace88aa59301eb47eafc93db45af3/jenv.ps1#L3

**Comment by FelixSelter** [comment]
Changed it: https://github.com/FelixSelter/JEnv-for-Windows/commit/69ed4e4be2cd8d6dfd127269b1e16b90bc611cac

**Comment by FelixSelter** [comment]
Thank you for your contribution
