### ISSUE TITLE
Extra output on first run

### ISSUE THREAD

**Issue by bkmeneguello** [FelixSelter/JEnv-for-Windows#19]
On the first execution, when the `jenv.config` file doesn't exist, some extra text is printed to console:
```
jenv list                                                                             0ms

    Directory: C:\Users\<me>\AppData\Roaming

Mode                 LastWriteTime         Length Name
----                 -------------         ------ ----
d----          17/04/2012    01:33                JEnv
__JEnvs__
```

I think it's missing a `| Out-Null` [here](https://github.com/FelixSelter/JEnv-for-Windows/blob/af878ff7f4e1c99c308319d9e768ebb881dfcf34/jenv.ps1#L163).

**Comment by FelixSelter** [comment]
oh. i thought i already catched that one. i will look into your issues as fast as possible but I do not have much time lately
