### ISSUE TITLE
Jenv change throws error: setx is not recognized as an internal or external command

### ISSUE THREAD

**Issue by treaz** [FelixSelter/JEnv-for-Windows#2]
Jenv change seems broken. Or maybe I'm not reading the docs wrongly.
I've tried running the script from cmd and powershell with the same result

```
C:\Users\hconstantin\dev>jenv list
jdk11|"C:\Program Files\Java\jdk-11.0.10"
jdk8|"C:\Program Files\Java\jdk1.8.0_211"

C:\Users\hconstantin\dev>jenv change jdk11
Latest version installed is 16.9.31229.75
Located msbuild in C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\MSBuild\Current\Bin\msbuild.exe
'setx' is not recognized as an internal or external command,
operable program or batch file.
Changed to jdk11

C:\Users\hconstantin\dev>java -version
'java' is not recognized as an internal or external command,
operable program or batch file.
```

**Comment by FelixSelter** [comment]
Hello,
Im sorry that you have trouble with the application.

As far as I know this only happens on your machine. I will look as fast as possible into it but Im currently not at home.

For now I would suggest trying some of these suggestions. https://stackoverflow.com/questions/34482278/setx-command-not-recognized-on-windows10

You could try to call setx and configure your path until its recognised. may copy the setx.exe into another folder and add it to the path.

Another option would be to change setx to set but be aware that it will delete your path if its over a certain size.

I will reply again when Im back and could look into your two issues

**Comment by FelixSelter** [comment]
Hello,
Im sorry that you have trouble with the application.

As far as I know this only happens on your machine. I will look as fast as possible into it but Im currently not at home.

For now I would suggest trying some of these suggestions. https://stackoverflow.com/questions/34482278/setx-command-not-recognized-on-windows10

You could try to call setx and configure your path until its recognised. may copy the setx.exe into another folder and add it to the path.

Another option would be to change setx to set but be aware that it will delete your path if its over a certain size.

I will reply again when Im back and could look into your two issues

Tell me if you would be open to a remote session so I may could take a look at you operating system if necessary

**Comment by treaz** [comment]
setx is already on my path in cmd. See below.
```
C:\Users\hconstantin>setx
ERROR: Invalid syntax.
Type "SETX /?" for usage.

C:\Users\hconstantin>
```

Thanks for looking into this together Felix, I really like jenv and I'm open to do a remote session to fix this as fast as possible.

**Comment by FelixSelter** [comment]
I think Im rewriting this today in Powershell so this project is more scalable and should still run on any windows

**Comment by FelixSelter** [comment]
> 
> 
> setx is already on my path in cmd. See below.
> 
> ```
> C:\Users\hconstantin>setx
> ERROR: Invalid syntax.
> Type "SETX /?" for usage.
> 
> C:\Users\hconstantin>
> ```
> 
> Thanks for looking into this together Felix, I really like jenv and I'm open to do a remote session to fix this as fast as possible.

I rewrote the entire script in PowerShell which should run much better and safer from now on. Also now there's no setx anymore which was not working for you. I will close your two issues as the source code is now entirely new. Please refer to the readme. If it doesn't work for you please open another issue. I'm happy to help

The script should now be less error-prone as it will automatically remove any wrong java form you path and the config wont break as easy. But be aware that you need to create a new jenf.config Please delete your old one
