### ISSUE TITLE
Error when powershell.exe is not in the PATH

### ISSUE THREAD

**Issue by bkmeneguello** [FelixSelter/JEnv-for-Windows#21]
I don't have `C:\WINDOWS\System32\WindowsPowerShell\v1.0\` in my PATH because I use the portable PowerShell, which is installed as `C:\Program Files\PowerShell\7\pwsh.exe`. It could be possible to check if it exists and use it before trying the windows build-in?
```
jenv change openjdk17
'Powershell.exe' is not recognized as an internal or external command,
operable program or batch file.
```

**Comment by FelixSelter** [comment]
This will be implemented in Version 2 a complete rewrite of this application which should be more scalable and support tests as well as being more close to the original

**Comment by FelixSelter** [comment]
version 2 is now published and contains this feature.
Please report any bugs.

Thank you for your suggestion

**Comment by FelixSelter** [comment]
Ah, damn it. Github closed it because of my commit message. I pushed an update. Now JEnv asks you to restart with admin rights so it can change the system path. Thank you for your suggestion. Please report any further problems
