### ISSUE TITLE
Every invocation results in "JEnv is changing your environmental variables"

### ISSUE THREAD

**Issue by serg06** [FelixSelter/JEnv-for-Windows#24]
I just installed jenv. Every time I do `jenv list`, I get this output:

```cmd
C:\Users\Name>jenv list
JEnv is changing your environment variables. This process could take longer but it happens only when a java executable is found in your path
All avaible versions of java

All locally specified versions


```

And when I trigger it again, I get this output:

```cmd
C:\Users\Name>jenv list
'where' is not recognized as an internal or external command,
operable program or batch file.
'where' is not recognized as an internal or external command,
operable program or batch file.
Neither pwsh.exe nor powershell.exe was found in your path.
Please install powershell it is required

```

Forcing me to restart my terminal. 

When I restart it, the whole process repeats itself.

**Comment by FelixSelter** [comment]
Yea that's how it's supposed to be. I pushed hopefully a fix. Please test it.

**Comment by FelixSelter** [comment]
Now the script should remove at least any java from the user path. There could still be issues if you have java inside your system/machine path but java does not put them there when installed. Where java should only point to jenvs java.bat

**Comment by serg06** [comment]
@FelixSelter The two .exes are still there, due to being in my System's PATH, but I might have added them there manually, I don't remember.

> There could still be issues if you have java inside your system/machine path but java does not put them there when installed.

If you don't remove them from the System's PATH, perhaps you could give a warning that the user needs to do it manually?

**Comment by FelixSelter** [comment]
Hi, Please update again. I changed the code so it requests you to restart with admin rights so it can automatically correct the system path. Thank you for your suggestion. Can this be closed now?

**Comment by serg06** [comment]
Seems to work, thanks!
