### ISSUE TITLE
How to uninstall jenv

### ISSUE THREAD

**Issue by Kyanite0029** [FelixSelter/JEnv-for-Windows#25]
I installed it because I want to control the Java version, but there is a problem with my computer, so I want to delete jenv. How can I delete jenv and restore my java?

**Comment by FelixSelter** [comment]
Hi, Im sorry youre experienced issues with JEnv. Please tell them to me so I can fix them. If you want to uninstall JEnv you have to delete its folder. If you want to restore youre java versions you can navigate to "%appdata%/JEnv" Just enter this into the path of youre explorer. There should be a file called JEnv.config.json. Right click and open with your text editor of choice. There you will find your added java versions. Copy the path of the desired version it should look somewhat like "C://Program Files/Java/jre-1.81/" now copy it and add bin to the end. It should now look like this: "C://Program Files/Java/jre-1.81/bin/" Search using the windows search bar for "edit environment variables" then click edit somewhere to the bottom right. A new window should open. Search for path in the upper table. Should be in the first column. Double click and a list should open. Click new on the right. Now paste youre path to java and click ok. Restart terminal and it should work. I will add a uninstall feature soon. Will be posting images shortly so you can understand better

**Comment by Kyanite0029** [comment]
thanks you

**Comment by FelixSelter** [comment]
![1](https://user-images.githubusercontent.com/55546882/159115195-e8ca20e4-2479-4372-a67e-941e30a58490.png)
![2](https://user-images.githubusercontent.com/55546882/159115197-cc65e6f3-b5ee-40a4-ac6f-68d41c6f1d96.png)
![3](https://user-images.githubusercontent.com/55546882/159115198-306b39e4-0575-4e8f-8cff-034654e77287.png)
![4](https://user-images.githubusercontent.com/55546882/159115250-60296082-5f4b-41fe-b434-4736fbe96d7a.png)
![5](https://user-images.githubusercontent.com/55546882/159115203-46efd04e-654a-4930-8f81-657555d1ce31.png)
![6](https://user-images.githubusercontent.com/55546882/159115204-b5b09e12-537d-44b9-babf-8a485b80f777.png)
![7](https://user-images.githubusercontent.com/55546882/159115205-21116c79-ea55-4210-9d3b-c4421bbee761.png)
![8](https://user-images.githubusercontent.com/55546882/159115207-19db9e57-4fd0-4fd5-ad1f-2e42bc72021a.png)
