### ISSUE TITLE
Commands other than java do not work

### ISSUE THREAD

**Issue by h4iku** [FelixSelter/JEnv-for-Windows#26]
Hi, thanks for the great tool.

I upgraded my installation by pulling from the repository and adding my JDKs back. Now commands like `javac` or `jshell` don't work.

```
❯ java -version
openjdk version "11.0.14.1" 2022-02-08
OpenJDK Runtime Environment Temurin-11.0.14.1+1 (build 11.0.14.1+1)
OpenJDK 64-Bit Server VM Temurin-11.0.14.1+1 (build 11.0.14.1+1, mixed mode)
❯ javac
javac: The term 'javac' is not recognized as a name of a cmdlet, function, script file, or executable program.
Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
❯ jshell
jshell: The term 'jshell' is not recognized as a name of a cmdlet, function, script file, or executable program.
Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
```

Since the `java` command is processed through `java.bat`, I guess every command needs its own bat file now?

**Comment by FelixSelter** [comment]
Yea thats right. It was just a matter of time till someone asks that question. You have to copy java.bat rename it to javac.bat and replace any "java" inside with "javac"

When I fixed your other issue I will create a command to add these batch files automatically

**Comment by FelixSelter** [comment]
Hi. I added the "jenv link" command.
Use it like this: "jenv link javac"; "jenv link shell"; "jenv link <executable>"
Can this be closed now?

**Comment by h4iku** [comment]
Works great.
Thank you.
