### ISSUE TITLE
maybe add command to clean invalid *name-path* in `jenv.config.json`

### ISSUE THREAD

**Issue by potoo0** [FelixSelter/JEnv-for-Windows#30]
sometimes there are temp folder set jdk version, and after that we need to clean up those invaild *name-path* config.

**Comment by FelixSelter** [comment]
Sorry I dont get what you mean?
Can you maybe add an example of how the config looks before and what you expect it to look like after running the command

**Comment by potoo0** [comment]
The known `jenv.config.json` content is

```json
{
  "jenvs":[...],
  "locals":[
    {
      "path":"E:\\test_jshell",
      "name":"jdk17"
    },
    {
      "path":"E:\\test_jshell\\build\\libs",
      "name":"jdk17"
    },
    {
      "path":"E:\\test_jshell\\build\\libs\\Template",
      "name":"jdk17"
    }
  ],
  "global":"D:\\Java\\jdk1.8.0_261"
}
```

Those *name-path* in *locals* will not vaild , after I delete E:\\test_jshell folder. I expect there was a command to clear those.

**Comment by FelixSelter** [comment]
well you can just go into the folder and type `jenv local remove` before you delete it?  
Im not exactly sure why we would need an additional feature?  
Tell me if that solved your problem or i will implement it so it checks at every run if folders got deleted

**Comment by FelixSelter** [comment]
?
