### ISSUE TITLE
win10无法切换全局版本

### ISSUE THREAD

**Issue by jobsgxx** [FelixSelter/JEnv-for-Windows#33]
![image](https://user-images.githubusercontent.com/45745859/179432421-0df886f3-8a40-4dc6-bc74-88be4ba8ff26.png)

**Comment by FelixSelter** [comment]
Hi, can you please ensure that you use the latest version of jenv and provide you jenv.conf?

With ienv list you can check if you accidentally set jdk11 to jre8

**Comment by FelixSelter** [comment]
Does this issue still persist?

**Comment by FelixSelter** [comment]
I will close this now due go no response and no reproducibility. Feel free to open another one
