### ISSUE TITLE
Cannot change global variables for Windows10

### ISSUE THREAD

**Issue by cheshennull** [FelixSelter/JEnv-for-Windows#34]
![bug](https://user-images.githubusercontent.com/42889666/182313048-b8dee1f7-6f0e-451a-9605-5499b1e16367.png)

**Comment by FelixSelter** [comment]
Hi, thanks for using jenv

Are you still using an old version of jenv?
If so please update and tell me if the issue persists.

**Comment by cheshennull** [comment]
Now i update newest version,question is solving.
Thanks Sir.

**Comment by FelixSelter** [comment]
Glad to hear that everything is working fine now.
