### ISSUE TITLE
Autoaccept defaults on "jenv autoscan"

### ISSUE THREAD

**Issue by rcsilva83** [FelixSelter/JEnv-for-Windows#39]
Add a parameter like `-y` to autoaccept the java versions and suggested names, so there is no user prompt and this can be used on scripts to automate the developer environment configuration.

**Comment by FelixSelter** [comment]
I suggest we pair this feature with a --template java%version% flag. In  #36 we plan on changing the default name only to the major version. Would this break anything for you?

**Comment by rcsilva83** [comment]
No, I think it makes it simpler as we won't work with multiple JDK's with the same major version.
