### ISSUE TITLE
A command to delete an entry from the jenv.config

### ISSUE THREAD

**Issue by FelixSelter** [FelixSelter/JEnv-for-Windows#4]
jenv delete <name>

Should be pretty self-explaining.
This is a simple task.
The project is very small too so it should be easy for beginners to contribute.
If you have any questions just ask.

I'm looking forward to your contribution

**Comment by treaz** [comment]
I'm happy to pick this one up, however I'd like to call it jenv remove (as it is named on the original jenv implementation)
