### ISSUE TITLE
JEnv is changing your environment variables. This process could take longer but it happens only when a jenv executable is found in your path

### ISSUE THREAD

**Issue by dibog** [FelixSelter/JEnv-for-Windows#49]
Hi,

I like the idea of this tool, like pyenv or nvm. I installed it and am testing it right now.
But somehow I can't get rid of 

```
JEnv is changing your environment variables. This process could take longer but it happens only when a jenv executable is found in your path
```

The tools seems to work, but everytime I'm using jenv it prints out the warning/text.
Why is that? Do I have something to do to get rid of?
The manual especially says I should put JRE on the Path.

Best regards,
Dieter

**Comment by FelixSelter** [comment]
Hi Dieter,
you could run JEnv with administrator rights so it can remove any java version from your computers path. Optionally you could do it on your own. Remove any jre or jdk from your users and computers path. If you need further assistance we are happy to help. However there should be a warning that tells you exactly this. We need to investigate. Therefore I leave this open.

Best regards,
Felix

**Comment by dibog** [comment]
Hi Felix,

that is unfortunatly not the case. I was running the commands within in a cmd shell with admin rights:

![grafik](https://user-images.githubusercontent.com/1060258/220838983-adb1a9ae-ac3b-485f-b0fa-11cd29490b24.png)

I can close this shell, open a new admin or normal cmd shell, and it still shows the same warning.

When I remove the path to JEnv-for-Windows and type java, I got then the message that there is no java on the path.
As soon as  I add JEnv-for-Windows to the path again it shows the warning.

Best regards,
Dieter

**Comment by FelixSelter** [comment]
Ok. I guess you are using the latest version of JEnv? Would you be open for an online trouble shooting meeting?

**Comment by dibog** [comment]
```C:\git\JEnv-for-Windows>git log
commit 0c882c9df3da24be8208866fa2799b8f10dc5828 (HEAD -> main, origin/main, origin/HEAD)
Author: FelixSelter <felixselterdeveloping@gmail.com>
Date:   Mon Jan 16 17:20:06 2023 +0000

    Inserted version into source file
```

Thats the last git log entry.

And regarding the meeting, I would have time now.

**Comment by FelixSelter** [comment]
You may join me (https://demo.bigbluebutton.org/rooms/mba-ksd-z7e-4ph/join) at 09:00 Munich time

**Comment by dibog** [comment]
> You may join me (https://demo.bigbluebutton.org/rooms/mba-ksd-z7e-4ph/join)
at 09:00 Munich time

Great, and where in München are you? I'm near the Rotkreuzplatz :-)

Best regards,
Dieter

Am Do., 23. Feb. 2023 um 08:38 Uhr schrieb FelixSelter <
***@***.***>:

**Comment by FelixSelter** [comment]
Actually I am near Mainz but I looked into your profile and saw that you are from Munich :)  
I was able to track down the issue to this commit: e47c521  
Therefore we do not need the meeting.
I am going to fix this soon.

**Comment by dibog** [comment]
Hi Felix,

great, just let me know when you fixed it and I will test it.

Best regards,
Dieter


Am Do., 23. Feb. 2023 um 08:49 Uhr schrieb FelixSelter <
***@***.***>:

**Comment by FelixSelter** [comment]
Can you test my changes?

**Comment by dibog** [comment]
Yep, the mesage it not longer appears. Thanks!
