### ISSUE TITLE
remove jenv.home.tmp and jenv.path.tmp after Invoke-Use

### ISSUE THREAD

**Issue by treaz** [FelixSelter/JEnv-for-Windows#7]
In the Invoke-Use, two temp files are created: jenv.home.tmp and jenv.path.tmp.
To keep things clean, it would be got to remove them after they're used

Or consider using this feature: $TempFile = New-TemporaryFile

**Comment by FelixSelter** [comment]
Those are necessary and will be deleted by the batch file. The Powershell script cant set environment variables for the parent shell. The batch script is executing the powershell script and is looking for these files. When it founds them it sets the environment vars for the shell and deletes them.

Please run the script via the batch file.

I will leave this open as I may miss understood something

**Comment by FelixSelter** [comment]
Please refer to #5 for additional information

**Comment by treaz** [comment]
Sorry for no being clear in the original message. I'll clarify.
When I run **jenv.ps1**, jenv.home.tmp and jenv.path.tmp get created, but they don't get deleted.
The code that creates them is here: 
https://github.com/FelixSelter/JEnv-for-Windows/blob/main/jenv.ps1#L68
https://github.com/FelixSelter/JEnv-for-Windows/blob/main/jenv.ps1#L82

It seems to me that jenv.ps1 doesn't use these files, so I guess that those lines can just be deleted

**Comment by treaz** [comment]
Oh, I thought that I'm supposed to use the ps1 script. I read the documentation more carefully and I see that I'm supposed to use jenv.bat

**Comment by FelixSelter** [comment]
My bad. I updated the readme. It was unclear. I thought it would be easier to run Jenv from any console and not just powershell so I implemented this kind of hack
