### ISSUE TITLE
Bug: Environments are missing when starting shell on different volume

### ISSUE THREAD

**Issue by Dakror** [FelixSelter/JEnv-for-Windows#9]
I created my environments with the CMD under C:/

When opening a CMD in a folder on my other drive (I:/) no envs are available.

**Comment by ParrySMS** [comment]
Hi @Dakror,

Could you please tell me which shell are you using? 

CMD, Powershell, or MS Terminal?

**Comment by FelixSelter** [comment]
Hello Dakror,
Could you specify what you mean with no envs are available?
On my second drive, everything is working fine. Maybe you forgot to reopen the shell after changing env vars from another shell?
However I fixed some issues maybe you can get back to me if the issue persists?

**Comment by Dakror** [comment]
Your update has seemingly fixed the issue for me, thank you! :)
